language: csharp
solution: MSTestAndSimpleStub.sln
dotnet: 2.1.104

script:
  - dotnet restore
  - ./build.sh
  - ./test.sh
  - grep "Test Results" build.log

install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore MSTestAndSimpleStub.sln

